[global]
strategy = 'packets'
log_level = 'error'

[[chains]]
id = 'applemint_9000-2'
rpc_addr = 'http://127.0.0.1:26657'
grpc_addr = 'http://127.0.0.1:9090'
websocket_addr = 'ws://localhost:26657/websocket'
rpc_timeout = '10s'
account_prefix = 'eth'
key_name = 'testkey'
store_prefix = 'ibc'
max_gas = 200000
gas_price = { price = 0.001, denom = 'aapple' }
max_msg_num = 4
max_tx_size = 1048576
clock_drift = '5s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
address_type = { derivation = 'ethermint', proto_type = { pk_type = '/ethermint.crypto.v1.ethsecp256k1.PubKey' } }



[[chains]]
id = 'pearmint_9000-6'
rpc_addr = 'http://127.0.0.1:26647'
grpc_addr = 'http://127.0.0.1:9080'
websocket_addr = 'ws://localhost:26647/websocket'
rpc_timeout = '10s'
account_prefix = 'eth'
key_name = 'testkey'
store_prefix = 'ibc'
gas_price = { price = 0.001, denom = 'apear' }
clock_drift = '5s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
address_type = { derivation = 'ethermint', proto_type = { pk_type = '/ethermint.crypto.v1.ethsecp256k1.PubKey' } }
