[global]
strategy = 'packets'
log_level = 'error'

[[chains]]
id = 'chainmain-1'
rpc_addr = 'http://127.0.0.1:26807'
grpc_addr = 'http://127.0.0.1:26806'
websocket_addr = 'ws://localhost:26657/websocket'
rpc_timeout = '10s'
account_prefix = 'cro'
key_name = 'testkey'
store_prefix = 'ibc'
max_gas = 200000
gas_price = { price = 0.001, denom = 'aapple' }
max_msg_num = 4
max_tx_size = 1048576
clock_drift = '5s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
address_type = { derivation = 'cosmos' }



[[chains]]
id = 'cronos_777-1'
rpc_addr = 'http://127.0.0.1:26707'
grpc_addr = 'http://127.0.0.1:26706'
websocket_addr = 'ws://localhost:26647/websocket'
rpc_timeout = '10s'
account_prefix = 'ethm'
key_name = 'testkey'
store_prefix = 'ibc'
gas_price = { price = 0.001, denom = 'apear' }
clock_drift = '5s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
address_type = { derivation = 'ethermint', proto_type = { pk_type = '/ethermint.crypto.v1.ethsecp256k1.PubKey' } }
